version: '3.3'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      - cluster.name=kick-a-lot
      - bootstrap.memory_lock=true
      - node.name=zizou
      - node.ml=false
      - xpack.ml.enabled=false
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=${SECURITY_ENABLED}
      - xpack.monitoring.enabled=${MONITORING_ENABLED}
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "fifa-data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    networks:
      - esnet

volumes:
  fifa-data:

networks:
  esnet:
