version: '3.3'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: kick-es
    environment:
      - cluster.name=kick-a-lot
      - bootstrap.memory_lock=true
      - node.name=zizou
      - node.ml=false
      - xpack.ml.enabled=false
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=${SECURITY_ENABLED}
      - xpack.monitoring.enabled=${MONITORING_ENABLED}
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "fifa-data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    networks: ['elastic-stack']
    restart: always
  ki01:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kick-it
    hostname: kibana
    ports: ['5601:5601']
    networks: ['elastic-stack']
    depends_on: ['es01']
    restart: on-failure
    environment:
      - XPACK_MONITORING_ENABLED=${MONITORING_ENABLED}
      - ELASTICSEARCH_HOSTS=http://kick-es:9200

volumes:
  fifa-data:

networks:
  elastic-stack:
